version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_bachelor_poc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bachelor_poc
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite_bachelor_poc
    ports:
      - '10000:10000' # Only need blob storage port
    command: azurite --blobHost 0.0.0.0 --blobPort 10000
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  azurite_data:
